<?php

namespace Proxies\__CG__\Acme\StoreBundle\Entity;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class Picture extends \Acme\StoreBundle\Entity\Picture implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }

    /** @private */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int) $this->_identifier["id"];
        }
        $this->__load();
        return parent::getId();
    }

    public function setPicFile(\Symfony\Component\HttpFoundation\File\UploadedFile $picFile = NULL)
    {
        $this->__load();
        return parent::setPicFile($picFile);
    }

    public function getPicFile()
    {
        $this->__load();
        return parent::getPicFile();
    }

    public function setPicPath($picPath)
    {
        $this->__load();
        return parent::setPicPath($picPath);
    }

    public function getPicPath()
    {
        $this->__load();
        return parent::getPicPath();
    }

    public function setPicTitle($picTitle)
    {
        $this->__load();
        return parent::setPicTitle($picTitle);
    }

    public function getPicTitle()
    {
        $this->__load();
        return parent::getPicTitle();
    }

    public function setPicAlt($picAlt)
    {
        $this->__load();
        return parent::setPicAlt($picAlt);
    }

    public function getPicAlt()
    {
        $this->__load();
        return parent::getPicAlt();
    }

    public function getPicAbsoluteWebPath()
    {
        $this->__load();
        return parent::getPicAbsoluteWebPath();
    }

    public function getWebPicPath()
    {
        $this->__load();
        return parent::getWebPicPath();
    }

    public function getUploadRootPicDir()
    {
        $this->__load();
        return parent::getUploadRootPicDir();
    }

    public function getUploadPicDir()
    {
        $this->__load();
        return parent::getUploadPicDir();
    }

    public function upload()
    {
        $this->__load();
        return parent::upload();
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'id', 'picPath', 'picTitle', 'picAlt');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields as $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}